"""add_duration_hours_location_to_posts

Revision ID: 064873a3a4f9
Revises: c9e5270ba9a2
Create Date: 2026-06-27 02:23:50.591240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064873a3a4f9'
down_revision: Union[str, Sequence[str], None] = 'c9e5270ba9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('duration_hours', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('location', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###
    # Autogenerate omits CheckConstraints — added manually:
    op.create_check_constraint(
        "ck_post_duration_hours_min1",
        "posts",
        "duration_hours IS NULL OR duration_hours >= 1",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_post_duration_hours_min1", "posts", type_="check")
    op.drop_column('posts', 'location')
    op.drop_column('posts', 'duration_hours')
    # ### end Alembic commands ###
