"""create bookings

Revision ID: 58513b7b7a7b
Revises: 300a647ca2cb
Create Date: 2026-06-21 21:21:39.658392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58513b7b7a7b'
down_revision: Union[str, Sequence[str], None] = '300a647ca2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('booking_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('tourist_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='booking_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('guide_id != tourist_id', name='ck_booking_guide_ne_tourist'),
    sa.ForeignKeyConstraint(['guide_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.slot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tourist_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('bookings')
    # autogenerate doesn't drop the enum type; do it explicitly so a
    # downgrade -> upgrade cycle doesn't fail with "type already exists".
    sa.Enum(name='booking_status').drop(op.get_bind(), checkfirst=True)
