"""add performance indexes

Revision ID: c9e5270ba9a2
Revises: 528c76e2546b
Create Date: 2026-06-22 14:30:22.477992

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c9e5270ba9a2'
down_revision: Union[str, Sequence[str], None] = '528c76e2546b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_guide_id'), 'bookings', ['guide_id'], unique=False)
    op.create_index(op.f('ix_bookings_slot_id'), 'bookings', ['slot_id'], unique=False)
    op.create_index(op.f('ix_bookings_tourist_id'), 'bookings', ['tourist_id'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_slots_date'), 'slots', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slots_date'), table_name='slots')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_bookings_tourist_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_slot_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_guide_id'), table_name='bookings')
    # ### end Alembic commands ###
